spring.application.name=flux_mono
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://127.0.0.1:5432/fluxmono}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:postgres}
spring.sql.init.mode=always
